version: '3'

services:
  vue-app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - /var/jenkins_home/workspace/VueJS:/app
    working_dir: /app
    command: npm run serve

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/jenkins_home/workspace/VueJS/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vue-app

