version: '3'

services:
  vue-app:
    build:
      context: .
    ports:
      - "8080:80"
    command: ["npx", "http-server", "dist", "-p", "80"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/jenkins_home/workspace/VueJS/nginx/default.conf
    depends_on:
      - vue-app

